### ISSUE TITLE
支持mps/cpu

### ISSUE THREAD

**Issue by kingzeus** [liasece/sd-webui-train-tools#11]
mac上训练的时候，返回
```
Train Tools: train.train error fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "/Users/kingzeus/Development/ai/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train_ui.py", line 121, in on_train_begin_click
    train.train(cfg)
  File "/Users/kingzeus/Development/ai/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train.py", line 68, in train
    train_network.train(args)
  File "/Users/kingzeus/Development/ai/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/train_network.py", line 119, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "/Users/kingzeus/Development/ai/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/library/train_util.py", line 2498, in prepare_accelerator
    accelerator = Accelerator(
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/accelerator.py", line 286, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
```

kohya_ss 设置的时候可以支持mps/cpu 模式，能否增加下支持？

**Comment by liasece** [comment]
你说的 kohya_ss 是哪个？我好像没看到 kohya_ss 有这个选项 https://github.com/bmaltais/kohya_ss/issues/328

**Comment by kingzeus** [comment]
mac上的setup.sh 默认生成的config 文件 ~/.cache/huggingface/accelerate/default_config.yaml
windows的setup.bat 支持配置，不过不太确定这个是不是会生效
