### ISSUE TITLE
ImportError: No xformers / xformersがインストールされていないようです

### ISSUE THREAD

**Issue by 13372053563** [liasece/sd-webui-train-tools#21]
您好，我在开始训练的时候遇到的如下情况：
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 23689.94it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1020
mean ar error (without repeats): 0.0
prepare accelerator
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
Train Tools: train.train error No xformers / xformersがインストールされていないようです
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/library/train_util.py", line 1672, in replace_unet_cross_attn_to_xformers
    import xformers.ops
ModuleNotFoundError: No module named 'xformers.ops'; 'xformers' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train_ui.py", line 121, in on_train_begin_click
    train.train(cfg)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train.py", line 68, in train
    train_network.train(args)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/train_network.py", line 134, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/library/train_util.py", line 1626, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/library/train_util.py", line 1674, in replace_unet_cross_attn_to_xformers
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです

请问这是什么问题，我第一次遇到这个问题找了一个解决方案是：Change '--force-enable-xformers' to '--xformers' guys.
但是我使用的python launch.py启动的程序，没有传入任何的参数。但是我也尝试修改了：启动后爆了memory的异常，去掉这'--xformers' 参数后又爆了core dumped。
我现在是重装了一个新的环境，重新运行的，第二次遇到了这个错误。

**Comment by liasece** [comment]
是否安装了其他训练插件？禁用其他插件试试
