### ISSUE TITLE
Error when exec "bash webui.sh"

### ISSUE THREAD

**Issue by realcarlos** [liasece/sd-webui-train-tools#23]
################################################################
Launching launch.py...
################################################################
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

Installing sd-webui-train-tools requirement: /home/dawei/stable-diffusion-webui/extensions/sd-webui-train-tools/requirements.txt

#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
Civitai Link revision: c4d4b2e374eccb5f192929a1332e46852f494173
SD-WebUI revision: 22bcc7be428c94e9408f589966c2040187245d81

Checking Civitai Link requirements...
[+] python-socketio[client] version 5.7.2 installed.

Error loading script: train_tools.py
Traceback (most recent call last):
  File "/home/test/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/test/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/test/stable-diffusion-webui/extensions/sd-webui-train-tools/scripts/train_tools.py", line 7, in <module>
    from liasece_sd_webui_train_tools.ui import *
  File "/home/test/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/ui.py", line 8, in <module>
    from liasece_sd_webui_train_tools.util import *
  File "/home/test/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/util.py", line 12, in <module>
    def readImages(inputPath: str, level: int = 0, include_pre_level: bool = False, endswith :str | list[str] = [".png",".jpg",".jpeg",".bmp",".webp"], startswith: str | list[str] = None) -> list[Image.Image]:
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

**Comment by liasece** [comment]
same #1
