### ISSUE TITLE
加载错误，错误如下

### ISSUE THREAD

**Issue by xionglikarl** [liasece/sd-webui-train-tools#24]
Error loading script: train_tools.py
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-train-tools/scripts/train_tools.py", line 7, in <module>
    from liasece_sd_webui_train_tools.ui import *
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/ui.py", line 8, in <module>
    from liasece_sd_webui_train_tools.util import *
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/util.py", line 12, in <module>
    def readImages(inputPath: str, level: int = 0, include_pre_level: bool = False, endswith :str | list[str] = [".png",".jpg",".jpeg",".bmp",".webp"], startswith: str | list[str] = None) -> list[Image.Image]:
TypeError: 'type' object is not subscriptable

**Comment by liasece** [comment]
检查 python 版本，尝试 3.10 python版本
