### ISSUE TITLE
Script.run() missing 3 required positional arguments

### ISSUE THREAD

**Issue by wukan1986** [liasece/sd-webui-train-tools#27]
训练完后自动测试模型报错。

```bash
save trained model to D:\sd-webui-aki-v4\outputs\train_tools\projects\yangmi\versions\v1\trains\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\yangmi-v1.safetensors
model saved.
Train Tools: preview checkpoint: yangmi-v1(outputs\train_tools\projects\yangmi\versions\v1\trains\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\yangmi-v1.safetensors) 1/3
Train Tools: txt2img: <lora:yangmi-v1:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper [7, '<lora:yangmi-v1:0.6>,<lora:yangmi-v1:0.7>,<lora:yangmi-v1:0.8>,<lora:yangmi-v1:1>', 0, '', 0, '', True, False, False, False, 0]
Train Tools: Error while processing <lora:yangmi-v1:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\preview.py", line 117, in preview_checkpoint
    processed = runner.run(p, *args)
TypeError: Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Train Tools: preview checkpoint: yangmi-v1-000004(outputs\train_tools\projects\yangmi\versions\v1\trains\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\yangmi-v1-000004.safetensors) 2/3

Train Tools: txt2img: <lora:yangmi-v1-000004:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper [7, '<lora:yangmi-v1-000004:0.6>,<lora:yangmi-v1-000004:0.7>,<lora:yangmi-v1-000004:0.8>,<lora:yangmi-v1-000004:1>', 0, '', 0, '', True, False, False, False, 0]
Train Tools: Error while processing <lora:yangmi-v1-000004:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\preview.py", line 117, in preview_checkpoint
    processed = runner.run(p, *args)
Train Tools: preview checkpoint: yangmi-v1-000002(outputs\train_tools\projects\yangmi\versions\v1\trains\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\yangmi-v1-000002.safetensors) 3/3
TypeError: Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Train Tools: txt2img: <lora:yangmi-v1-000002:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper [7, '<lora:yangmi-v1-000002:0.6>,<lora:yangmi-v1-000002:0.7>,<lora:yangmi-v1-000002:0.8>,<lora:yangmi-v1-000002:1>', 0, '', 0, '', True, False, False, False, 0]
Train Tools: Error while processing <lora:yangmi-v1-000002:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\preview.py", line 117, in preview_checkpoint
    processed = runner.run(p, *args)
TypeError: Script.run() missing 3 required positional arguments: 'include_sub_grids', 'no_fixed_seeds', and 'margin_size'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Train Tools: in get_checkpoint_preview_images: project: yangmi v1 chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64 yangmi-v1: xyz_grid 0, sub_grid 0, all_img 0
Train Tools: in get_checkpoint_preview_images: project: yangmi v1 chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64 yangmi-v1-000004: xyz_grid 0, sub_grid 0, all_img 0
Train Tools: in get_checkpoint_preview_images: project: yangmi v1 chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64 yangmi-v1-000002: xyz_grid 0, sub_grid 0, all_img 0
```

**Comment by wukan1986** [comment]
我发现将 5月2号的版本切换成 3月29号的版本就不报这三个参数的错误了

**Comment by liasece** [comment]
已修复 https://github.com/liasece/sd-webui-train-tools/commit/cb6d59eb7dd1ae462917207867622e9606285bb6
