### ISSUE TITLE
无法生成预览图

### ISSUE THREAD

**Issue by wukan1986** [liasece/sd-webui-train-tools#29]
在3月29号的版本下，生成预览图报错
感觉是默认提供的正向提示词产生的路径非法，导致报错

`best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper`

```bash
Total progress: 223it [04:14, 11.71it/s]Train Tools: Error while processing <lora:yangmi-v1:0.6>, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper [Errno 2] No such file or directory: 'outputs\\train_tools\\projects\\yangmi\\versions\\v1\\trains\\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\\yangmi-v1\\images\\xyz_grid-0000-1944501389-_lora_yangmi-v1_0.6_, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper.tmp'
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\preview.py", line 117, in preview_checkpoint
    processed = runner.run(p, *args)
  File "D:\sd-webui-aki-v4\scripts\xyz_grid.py", line 675, in run
    images.save_image(processed.images[g], p.outpath_grids, "xyz_grid", info=processed.infotexts[g], extension=opts.grid_format, prompt=processed.all_prompts[adj_g], seed=processed.all_seeds[adj_g], grid=True, p=processed)
  File "D:\sd-webui-aki-v4\modules\images.py", line 584, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "D:\sd-webui-aki-v4\modules\images.py", line 554, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'outputs\\train_tools\\projects\\yangmi\\versions\\v1\\trains\\chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64\\yangmi-v1\\images\\xyz_grid-0000-1944501389-_lora_yangmi-v1_0.6_, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper.tmp'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Train Tools: in get_checkpoint_preview_images: project: yangmi v1 chilloutmix_NiPrunedFp32Fix-bs-1-ep-6-op-Lion-lr-0_0001-net-64-ap-64 yangmi-v1: xyz_grid 0, sub_grid 0, all_img 0
```

**Comment by liasece** [comment]
已修复 https://github.com/liasece/sd-webui-train-tools/commit/cb6d59eb7dd1ae462917207867622e9606285bb6
