### ISSUE TITLE
同时设置多个训练参数后出错

### ISSUE THREAD

**Issue by zero-kappa** [liasece/sd-webui-train-tools#34]
同时训练多个参数(如图1），生成preview图片时，程序报错：
Error completing request
Arguments: ('task(mzhjbhokm37k30w)', 'mountain', 'v4', 'anything-v3-bs-8-ep-20-op-Adam-lr-0_0001-net-128-ap-64', False, 'A picture of a single mountain, best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper', 'low quality, out of frame', ['Euler a', 'DPM++ SDE', 'DPM++ 2M SDE'], '30', 512, 512, 1, 8, '10', '-1', '0.6,0.7,0.8,1') {}
Traceback (most recent call last):
  File "/data/xuhaoran/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/data/xuhaoran/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/data/xuhaoran/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/checkpoint_preview_ui.py", line 199, in on_ui_preview_generate_all_preview_btn_click
    preview.preview_checkpoint(save_image_path, checkpoint_name, checkpoint_path,
  File "/data/xuhaoran/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/preview.py", line 96, in preview_checkpoint
    args+=[find_index_in_current_axis_options("Sampler"), preview_sampling_method.join(",")]
AttributeError: 'list' object has no attribute 'join'

Traceback (most recent call last):
  File "/data/xuhaoran/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/xuhaoran/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/data/xuhaoran/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1257, in postprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Box'> Component with id 2250 not a valid output component.

![image](https://github.com/liasece/sd-webui-train-tools/assets/135289068/b9c34eed-169c-4d92-a0dc-c5f77e9a030d)
![image](https://github.com/liasece/sd-webui-train-tools/assets/135289068/4823d220-e6d0-4569-9de9-6371d5f51231)

**Comment by liasece** [comment]
现在你可以更新本插件并重试。
