### ISSUE TITLE
New install broke vladmandic's automatic server

### ISSUE THREAD

**Issue by taxen** [liasece/sd-webui-train-tools#35]
I tried to install the extension on vladmandic's [automatic](https://github.com/vladmandic/automatic). When I restarted the server I got the following error and could not launch the server.

> \> H:\vladmandic\automatic>webui.bat --upgrade --lowvram
Using VENV: H:\vladmandic\automatic\venv
20:47:30-406615 INFO     Starting SD.Next
20:47:30-415755 INFO     Python 3.10.6 on Windows
20:47:30-502758 INFO     Version: c02ccc4f Tue Jun 20 13:49:00 2023 +0300
20:47:31-051184 INFO     Updating main repository
20:47:35-082433 INFO     Upgraded to version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
20:47:35-137285 INFO     Using CPU-only Torch
20:47:37-506274 INFO     Torch 2.0.0+cpu
20:47:37-725231 INFO     Verifying requirements
20:47:37-752159 INFO     Verifying packages
20:47:37-755152 INFO     Installing repositories
20:47:42-667844 INFO     Installing submodules
20:47:47-591243 INFO     Updating submodules
20:49:14-713510 INFO     Extension installed packages: sd-webui-train-tools
                         ['opencv-python-headless==4.7.0.72', 'albumentations==1.3.1',
                         'scikit-learn==1.2.2', 'joblib==1.2.0', 'diffusers==0.10.2',
                         'qudida==0.0.4']
20:49:21-844062 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext',
                         'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg',
                         'SwinIR', 'sd-webui-infinite-image-browsing', 'sd-webui-train-tools',
                         'sd_civitai_extension']
20:49:21-859588 INFO     Updating Wiki
20:49:24-020204 INFO     Extension preload: 0.0s
                         H:\vladmandic\automatic\extensions-builtin
20:49:24-027076 INFO     Extension preload: 0.0s H:\vladmandic\automatic\extensions
20:49:24-049928 INFO     Server arguments: ['--upgrade', '--lowvram']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

> Original exception was:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\launch.py", line 189, in <module>
    instance = start_server(immediate=True, server=None)
  File "H:\vladmandic\automatic\launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\vladmandic\automatic\webui.py", line 45, in <module>
    from modules import shared, extensions, extra_networks, ui_tempdir, ui_extra_networks, modelloader
  File "H:\vladmandic\automatic\modules\ui_extra_networks.py", line 8, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "H:\vladmandic\automatic\modules\generation_parameters_copypaste.py", line 10, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "H:\vladmandic\automatic\modules\images.py", line 17, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "H:\vladmandic\automatic\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors, shared
  File "H:\vladmandic\automatic\modules\sd_samplers_diffusors.py", line 1, in <module>
    from diffusers import (
ImportError: cannot import name 'DEISMultistepScheduler' from 'diffusers' (H:\vladmandic\automatic\venv\lib\site-packages\diffusers\__init__.py)

I guessed that the new install went wrong. So I deleted sd-webui-train-tools folder completely under automatic\extensions directory. Then I launched the server again and got this error.

> \>webui.bat --upgrade --lowvram
Using VENV: H:\vladmandic\automatic\venv
21:18:55-668066 INFO     Starting SD.Next
21:18:55-683684 INFO     Python 3.10.6 on Windows
21:18:55-777386 INFO     Version: 9740b9d2 Thu Jun 22 07:46:48 2023 -0400
21:18:56-183540 INFO     Using CPU-only Torch
21:18:58-401768 INFO     Torch 2.0.0+cpu
21:18:58-682952 INFO     Disabled extensions-builtin: ['stable-diffusion-webui-images-browser']
21:18:58-682952 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris',
                         'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-rembg',
                         'SwinIR']
21:18:58-714197 INFO     Disabled extensions: ['stable-diffusion-webui-images-browser']
21:18:58-714197 INFO     Enabled extensions: ['sd-webui-infinite-image-browsing',
                         'sd_civitai_extension']
21:18:58-714197 INFO     No changes detected: Quick launch active
21:18:58-729818 INFO     Extension preload: 0.0s
                         H:\vladmandic\automatic\extensions-builtin
21:18:58-729818 INFO     Extension preload: 0.0s H:\vladmandic\automatic\extensions
21:18:58-745440 INFO     Server arguments: ['--upgrade', '--lowvram']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "H:\vladmandic\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

> Original exception was:
Traceback (most recent call last):
  File "H:\vladmandic\automatic\launch.py", line 189, in <module>
    instance = start_server(immediate=True, server=None)
  File "H:\vladmandic\automatic\launch.py", line 136, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\vladmandic\automatic\webui.py", line 45, in <module>
    from modules import shared, extensions, extra_networks, ui_tempdir, ui_extra_networks, modelloader
  File "H:\vladmandic\automatic\modules\ui_extra_networks.py", line 8, in <module>
    from modules.generation_parameters_copypaste import image_from_url_text
  File "H:\vladmandic\automatic\modules\generation_parameters_copypaste.py", line 10, in <module>
    from modules import shared, ui_tempdir, script_callbacks, images
  File "H:\vladmandic\automatic\modules\images.py", line 17, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors, paths
  File "H:\vladmandic\automatic\modules\sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors, shared
  File "H:\vladmandic\automatic\modules\sd_samplers_diffusors.py", line 1, in <module>
    from diffusers import (
ImportError: cannot import name 'DEISMultistepScheduler' from 'diffusers' (H:\vladmandic\automatic\venv\lib\site-packages\diffusers\__init__.py)

Did the install change anything other than the files under under automatic\extensions\sd-webui-train-tools?

**Comment by taxen** [comment]
As I wrote in the related topic, I gave up installing the extension. Please refer to the topic for improving. Thank you.
