### ISSUE TITLE
现在遇到装了之后界面上没有插件入口，有人遇到过吗？

### ISSUE THREAD

**Issue by nickhanxj** [liasece/sd-webui-train-tools#36]
怀疑是插件冲突了，没有思路从哪里去看，请好心人帮忙解答一下，感激！

**Comment by liasece** [comment]
命令行中有报错吗？

**Comment by nickhanxj** [comment]
@liasece 没有，启动和运行时都看了日志，所以就不知道从哪里去看错误日志了

**Comment by liasece** [comment]
可以尝试将所有其他插件都禁用

**Comment by nickhanxj** [comment]
从另一个地方找到了错误日志
```
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "/home/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/stable-diffusion-webui/extensions/sd-webui-train-tools/scripts/train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "/home/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/ui.py", line 8, in <module>
        from liasece_sd_webui_train_tools.util import *
      File "/home/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/util.py", line 12, in <module>
        def readImages(inputPath: str, level: int = 0, include_pre_level: bool = False, endswith :str | list[str] = [".png",".jpg",".jpeg",".bmp",".webp"], startswith: str | list[str] = None) -> list[Image.Image]:
    TypeError: 'type' object is not subscriptable

```
麻烦帮忙看下呢

**Comment by liasece** [comment]
检查 python 版本，尝试 3.10 python版本

**Comment by nickhanxj** [comment]
@liasece 非常感谢，换成3.10版本已经ok了，适用了一下，非常好用！！！
