### ISSUE TITLE
UnboundLocalError: local variable 'train_name' referenced before assignment

### ISSUE THREAD

**Issue by xiaxiaxiaxia** [liasece/sd-webui-train-tools#40]
Train Tools: get_project_list: outputs\train_tools\projects\hangge
Train Tools: get_project_version_list: outputs\train_tools\projects\hangge\versions\1.0
Train Tools: ui_refresh_project: ['hangge']
Train Tools: on_ui_change_project_version_click: hangge 1.0
Train Tools: on_ui_change_project_click: hangge
Train Tools: get_project_version_list: outputs\train_tools\projects\hangge\versions\1.0
Train Tools: unknown base model
Train Tools: unknown base model
Train Tools: unknown base model
Train Tools: unknown base model
*** Error completing request
*** Arguments: ('task(e1euh7udxusotk0)', 'hangge', '1.0', None, 1.0, 20.0, 500.0, False, ['Lion'], '0.0002,0.0003,0.0004,0.0005', 128.0, 64.0, 500.0, 'fp16', True, False, False, 'best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper', 'low quality', ['Euler a'], '28', 512, 512, 1, 1, '10', '-1', '0.6,0.7,0.8,1') {}
    Traceback (most recent call last):
      File "D:\happy\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\happy\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\happy\stable-diffusion-webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 147, in on_train_begin_click
        return [None]+gr_update_trains_area_list(project, version, train_name)+["done"]
    UnboundLocalError: local variable 'train_name' referenced before assignment

---
Traceback (most recent call last):
  File "D:\happy\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\happy\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\happy\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1257, in postprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Box'> Component with id 1491 not a valid output component.

**Comment by jingzhengli** [comment]
I have the same error with you

**Comment by liasece** [comment]
same #43

**Comment by liasece** [comment]
fixed
