### ISSUE TITLE
ModuleNotFoundError: No module named 'networks.lora'

### ISSUE THREAD

**Issue by showmethecode1024** [liasece/sd-webui-train-tools#43]
[Dataset 0]
loading image sizes.
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 512
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
import network module: networks.lora
Train Tools: train.train error No module named 'networks.lora'
Traceback (most recent call last):
  File "E:\AI\stablediffusion\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 124, in on_train_begin_click
    train.train(cfg)
  File "E:\AI\stablediffusion\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 37, in train
    train_network.train(args)
  File "E:\AI\stablediffusion\sd-webui-aki-v4\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\sd_scripts\train_network.py", line 153, in train
    network_module = importlib.import_module(args.network_module)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'networks.lora'

**Comment by jingzhengli** [comment]
I also met this error. But I don't know how to fix it.

**Comment by Shigeto-Amatake** [comment]
I also met this error from version 1.5.0 of webui.
I like this tool a lot and hope it continues to grow.
I hope it will support SDXL as well.

**Comment by liasece** [comment]
I'm trying to resolve this issue. You can bypass this by reverting the webui version to https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7d26c479eebec03c2abb28f7b5226791688a7cea

**Comment by liasece** [comment]
fixed
