### ISSUE TITLE
train.train error No module named 'networks.lora'; 'networks' is not a package

### ISSUE THREAD

**Issue by kingfo** [liasece/sd-webui-train-tools#46]
我遇到问题如下：

```
import network module: networks.lora
Train Tools: train.train error No module named 'networks.lora'; 'networks' is not a package
Traceback (most recent call last):
  File "/Users/mbp/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train_ui.py", line 127, in on_train_begin_click
    train.train(cfg)
  File "/Users/mbp/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/train.py", line 37, in train
    train_network.train(args)
  File "/Users/mbp/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/sd_scripts/train_network.py", line 153, in train
    network_module = importlib.import_module(args.network_module)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1001, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'networks.lora'; 'networks' is not a package
```

MacBook Pro Apple M2 Max

**Comment by sanxibengbeng** [comment]
got this error also, waiting for solution

**Comment by liasece** [comment]
fixed
