### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by w43322** [liasece/sd-webui-train-tools#52]
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
E:\stable-diffusion-webui\system\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools.
*** Command: "E:\stable-diffusion-webui\system\python\python.exe" "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
***     repo.git.submodule("update", "--init", "--recursive", "--force")
***   File "E:\stable-diffusion-webui\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
***     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
***   File "E:\stable-diffusion-webui\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
***     return self.execute(call, **exec_kwargs)
***   File "E:\stable-diffusion-webui\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
***     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
***   cmdline: git submodule update --init --recursive --force
***   stderr: 'git: 'submodule' is not a git command. See 'git --help'.'
Launching Web UI with arguments:
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "E:\stable-diffusion-webui\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 22, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
    ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

---
```

**Comment by liasece** [comment]
重新从官网下载git并安装

**Comment by cenyan326** [comment]
点击训练时，训练时间就只有几秒，无法进行训练该怎么办？
