### ISSUE TITLE
文件中有stable-diffusion-webui/extensions/sd-webui-train-tools,但是UI界面中没有显示

### ISSUE THREAD

**Issue by Value-Jack** [liasece/sd-webui-train-tools#56]
终端显示Installing sd-webui-train-tools requirement: /home/lzj/code/sd_yj_oil/stable-diffusion-webui/extensions/sd-webui-train-tools/requirements.txt，一直卡在这里了，只装了stable-diffusion-webui-dataset-tag-editor这一个插件，想请问一下为什么没有train_tool选项，请问应该如何解决这个bug

**Comment by liasece** [comment]
麻烦提交完整的控制台日志以便确定问题所在。

**Comment by Value-Jack** [comment]
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements
Launching Web UI with arguments: --listen --port 8895 --device-id 1 --enable-insecure-extension-access --xformers --no-half
2024-03-04 20:40:08.176371: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-04 20:40:08.294058: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 20:40:08.648716: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 20:40:08.648807: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 20:40:08.685993: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-04 20:40:08.816278: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 20:40:08.817673: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-04 20:40:11.994257: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/lzj/anaconda3/envs/sd/lib/python3.9/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/home/lzj/anaconda3/envs/sd/lib/python3.9/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
Loading weights [7f96a1a9ca] from /home/lzj/code/sd_yj_oil/stable-diffusion-webui/models/Stable-diffusion/AnythingV5_v5PrtRE.safetensors
Running on local URL:  http://0.0.0.0:8895

To create a public link, set `share=True` in `launch()`.
preload_extensions_git_metadata for 9 extensions took 2.23s
Startup time: 24.8s (import torch: 12.3s, import gradio: 1.3s, import ldm: 3.6s, other imports: 2.1s, setup codeformer: 0.1s, load scripts: 2.1s, create ui: 1.2s, gradio launch: 2.0s).
Creating model from config: /home/lzj/code/sd_yj_oil/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 27.9s (load weights from disk: 4.3s, create model: 0.9s, apply weights to model: 6.2s, move model to device: 16.1s, calculate empty prompt: 0.4s).

################################################################
Launching launch.py...
################################################################
Cannot locate TCMalloc (improves CPU memory usage)
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements
Installing sd-webui-train-tools requirement: /home/lzj/code/sd_yj_oil/stable-diffusion-webui/extensions/sd-webui-train-tools/requirements.txt

Launching Web UI with arguments: --listen --port 8895 --device-id 1 --enable-insecure-extension-access --xformers --no-half
2024-03-04 20:41:40.481640: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-04 20:41:40.486579: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 20:41:40.568068: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-04 20:41:40.568217: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-04 20:41:40.570700: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-04 20:41:40.585700: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-04 20:41:40.586561: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-04 20:41:42.988578: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/lzj/anaconda3/envs/sd/lib/python3.9/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/home/lzj/anaconda3/envs/sd/lib/python3.9/site-packages/gradio_client/documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "/home/lzj/code/sd_yj_oil/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/lzj/code/sd_yj_oil/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/lzj/code/sd_yj_oil/stable-diffusion-webui/extensions/sd-webui-train-tools/scripts/train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "/home/lzj/code/sd_yj_oil/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/ui.py", line 8, in <module>
        from liasece_sd_webui_train_tools.util import *
      File "/home/lzj/code/sd_yj_oil/stable-diffusion-webui/extensions/sd-webui-train-tools/liasece_sd_webui_train_tools/util.py", line 12, in <module>
        def readImages(inputPath: str, level: int = 0, include_pre_level: bool = False, endswith :str | list[str] = [".png",".jpg",".jpeg",".bmp",".webp"], startswith: str | list[str] = None) -> list[Image.Image]:
    TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

---
Loading weights [7f96a1a9ca] from /home/lzj/code/sd_yj_oil/stable-diffusion-webui/models/Stable-diffusion/AnythingV5_v5PrtRE.safetensors
preload_extensions_git_metadata for 9 extensions took 1.60s
Running on local URL:  http://0.0.0.0:8895

To create a public link, set `share=True` in `launch()`.
Startup time: 19.6s (import torch: 9.8s, import gradio: 0.9s, import ldm: 2.7s, other imports: 1.7s, load scripts: 1.9s, create ui: 0.9s, gradio launch: 1.5s).
Creating model from config: /home/lzj/code/sd_yj_oil/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 24.0s (load weights from disk: 2.9s, create model: 1.1s, apply weights to model: 4.2s, move model to device: 15.4s, calculate empty prompt: 0.4s)

**Comment by liasece** [comment]
same #1 
see: https://github.com/liasece/sd-webui-train-tools/issues/1#issuecomment-1475936198
