### ISSUE TITLE
Not showing up.

### ISSUE THREAD

**Issue by AnzacA1** [liasece/sd-webui-train-tools#58]
I've installed via URL as instructed, but the new tab page is not appearing. The extension is enabled.

**Comment by liasece** [comment]
What error did the command line output?

**Comment by AnzacA1** [comment]
I'm not sure you understand the issue. I've installed the extension, it's in the list and it's enabled, but the new Tab for it isn't there.

**Comment by liasece** [comment]
Did you restart sd-webui after installing the extension?

**Comment by AnzacA1** [comment]
I did. Several times.

**Comment by liasece** [comment]
You should be reporting some errors on the command line running sd-webui, what does the cmd window output?

**Comment by AnzacA1** [comment]
Let me check quickly.

**Comment by AnzacA1** [comment]
"Error loading script: train_tools.py", then a a bunch of stuff, followed by "ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'".

**Comment by liasece** [comment]
Pls post the full log messages.

**Comment by AnzacA1** [comment]
Error loading script: train_tools.py
    Traceback (most recent call last):
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 23, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
    ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

**Comment by turbo-boo** [comment]
> Pls post the full log messages.

*** Error running install.py for extension C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools.
*** Command: "C:\Users\username\Downloads\webui_forge_cu121_torch21\system\python\python.exe" "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
***     repo.git.submodule("update", "--init", "--recursive", "--force")
***   File "C:\Users\username\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
***     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
***   File "C:\Users\username\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
***     return self.execute(call, **exec_kwargs)
***   File "C:\Users\username\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
***     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
***   cmdline: git submodule update --init --recursive --force
***   stderr: 'git: 'submodule' is not a git command. See 'git --help'.

*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "C:\Users\username\Downloads\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 23, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
    ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

I'm using forge diffusion on windows

**Comment by AnzacA1** [comment]
Same here. Also using Forge on Windows.

**Comment by liasece** [comment]
`stderr: 'git: 'submodule' is not a git command. See 'git --help'.` is the key.

Maybe your version of git is too old. Update git and try agin. Git for windows https://git-scm.com/download/win

**Comment by liasece** [comment]
Same https://github.com/liasece/sd-webui-train-tools/issues/14

**Comment by turbo-boo** [comment]
> `stderr: 'git: 'submodule' is not a git command. See 'git --help'.` is the key.
> 
> Maybe your version of git is too old. Update git and try agin. Git for windows https://git-scm.com/download/win

No, I've already installed latest git, but still showing that error

**Comment by AnzacA1** [comment]
Fully updated.

**Comment by liasece** [comment]
What does `git --version` output?

**Comment by AnzacA1** [comment]
Where do I put that?

**Comment by turbo-boo** [comment]
> What does `git --version` output?

git version 2.44.0.windows.1

**Comment by liasece** [comment]
This seems to be a bit complicated, for now, let's standardize the way we start sd-webui, let's start webui via git bash. you should be able to search for git bash in windows search

**Comment by AnzacA1** [comment]
Don't have git. Forge seemingly doesn't need it.

**Comment by liasece** [comment]
If you do this by just double-clicking webui-user.bat, I'm not sure where you'll be using your git to perform the action, as your git may not be in the PATH, or another git may be found in the PATH.

**Comment by AnzacA1** [comment]
Installing Git now. What editor should I use?

**Comment by liasece** [comment]
> Don't have git. Forge seemingly doesn't need it.

This plugin initialization requires git because it needs to pull the sd_script repository. What does this have to do with Forge?

**Comment by AnzacA1** [comment]
It's what I'm using! Which this Train Tool supposedly works with.

**Comment by AnzacA1** [comment]
Okay Git is installed. Now what?

**Comment by AnzacA1** [comment]
I'm getting MORE error messages now.

**Comment by AnzacA1** [comment]
Error running install.py for extension E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools.
*** Command: "E:\Pictures\Art Generation\webui_forge_cu121_torch21\system\python\python.exe" "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
***     repo.git.submodule("update", "--init", "--recursive", "--force")
***   File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
***     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
***   File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
***     return self.execute(call, **exec_kwargs)
***   File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
***     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
***   cmdline: git submodule update --init --recursive --force
***   stderr: 'git: 'submodule' is not a git command. See 'git --help'.'
Launching Web UI with arguments:
Total VRAM 12287 MB, total RAM 16310 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "E:\Pictures\Art Generation\webui_forge_cu121_torch21\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 23, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
    ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

**Comment by AnzacA1** [comment]
How do I launch Forge through Git Bash?

**Comment by liasece** [comment]
> How do I launch Forge through Git Bash?

An easy way to get started with git bash is to right click in your Forge file manager directory and select "Git Bash Here". Then run the start script.

**Comment by AnzacA1** [comment]
What's the file manager directory?

**Comment by turbo-boo** [comment]
Ok, I found why this module is not working.
The 1click package uses a prebuilt tool, so git cannot be used properly.
You can use it by using git clone and configuring it according to the manual.

**Comment by turbo-boo** [comment]
btw some errors occured during updating dataset
[error.txt](https://github.com/liasece/sd-webui-train-tools/files/14630822/error.txt)

**Comment by liasece** [comment]
> btw some errors occured during updating dataset [error.txt](https://github.com/liasece/sd-webui-train-tools/files/14630822/error.txt)

What is the format of the dataset image? It may be that the image format is not supported, try changing it to .png format.

**Comment by turbo-boo** [comment]
> > btw some errors occured during updating dataset [error.txt](https://github.com/liasece/sd-webui-train-tools/files/14630822/error.txt)
> 
> What is the format of the dataset image? It may be that the image format is not supported, try changing it to .png format.

serious? I was converting everything to jpg the other way around🤣

**Comment by turbo-boo** [comment]
can you add fp8 support btw? it is very useful for middle range graphic bords
