### ISSUE TITLE
downloaded,installation fails, and no tab on webui

### ISSUE THREAD

**Issue by redrainfalls** [liasece/sd-webui-train-tools#60]
Hi Boss, Thanks for the extension. As the title said, I tried to install train-tools in sd-webui-a1111 as instructed.  It appears to have been downloaded and I restarted it (number of times) but the installation failed and no tab shown on webui. Error message on console:

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Installing requirements for Face Editor
*** Error running install.py for extension D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools.*** Command: "D:\Program Files\sd-webui-a1111-v1-pre\system\python\python.exe" "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
***     repo.git.submodule("update", "--init", "--recursive", "--force")
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
***     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
***     return self.execute(call, **exec_kwargs)
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
***     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
***   cmdline: git submodule update --init --recursive --force
***   stderr: 'git: 'submodule' is not a git command. See 'git --help'.'
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --xformers --api --skip-version-check --ad-no-huggingface --theme dark
python_server_full_path:  D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 24.3.0, num models: 14
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet preprocessor location: D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-28 13:57:48,163 - ControlNet - INFO - ControlNet v1.1.441
2024-03-28 13:57:48,345 - ControlNet - INFO - ControlNet v1.1.441
sd-webui-prompt-all-in-one background API service started successfully.
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 23, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
    ModuleNotFoundError: No module named 'liasece_sd_webui_train_tools.sd_scripts.train_network'

---
Loading weights [b363551a70] from D:\Program Files\sd-webui-a1111-v1-pre\webui\models\Stable-diffusion\LEOSAM FilmGirl Ultra.safetensors
[LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
Creating model from config: D:\Program Files\sd-webui-a1111-v1-pre\webui\configs\v1-inference.yaml
2024-03-28 13:57:52,155 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: False
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy:
Civitai Helper: use civitai api key: False
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.
Model loaded in 5.0s (load weights from disk: 0.2s, create model: 2.8s, apply weights to model: 1.3s, load textual inversion embeddings: 0.4s, calculate empty prompt: 0.2s).

To create a public link, set `share=True` in `launch()`.
Startup time: 41.6s (prepare environment: 17.7s, import torch: 5.4s, import gradio: 1.4s, setup paths: 1.5s, initialize shared: 0.3s, other imports: 0.9s, load scripts: 6.4s, create ui: 2.8s, gradio launch: 2.6s, add APIs: 1.9s, app_started_callback: 0.7s).

**Comment by liasece** [comment]
same https://github.com/liasece/sd-webui-train-tools/issues/14

**Comment by redrainfalls** [comment]
![2024-03-28 14 59 13](https://github.com/liasece/sd-webui-train-tools/assets/152291794/596027d5-c94b-443a-a899-f6c9bb0a8970)

**Comment by redrainfalls** [comment]
I added the magic words "--enable-insecure-extension-access" in webui-user.bat

set COMMANDLINE_ARGS=--skip-torch-cuda-test --precision full --no-half --xformers --api --skip-version-check --ad-no-huggingface --enable-insecure-extension-access --theme dark

 but the error is the same.  I didn't think "--listen --port 7860" is the magic, or it is?

**Comment by redrainfalls** [comment]
and I am not literate enough to install a different git version inside the package, if that has been a solution, or not?

**Comment by liasece** [comment]
Now you can upgrade the extension and try again

**Comment by redrainfalls** [comment]
updated.  The error is a little different but still ends up not working.  See below:

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Installing requirements for Face Editor
*** Error running install.py for extension D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools.
*** Command: "D:\Program Files\sd-webui-a1111-v1-pre\system\python\python.exe" "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\install.py", line 8, in <module>
***     repo.git.submodule("update", "--init", "--recursive", "--force")
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 741, in <lambda>
***     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 1315, in _call_process
***     return self.execute(call, **exec_kwargs)
***   File "D:\Program Files\sd-webui-a1111-v1-pre\system\python\lib\site-packages\git\cmd.py", line 1109, in execute
***     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
***   cmdline: git submodule update --init --recursive --force
***   stderr: 'git: 'submodule' is not a git command. See 'git --help'.'
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --xformers --api --skip-version-check --ad-no-huggingface --enable-insecure-extension-access --theme dark
python_server_full_path:  D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 24.3.0, num models: 14
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet preprocessor location: D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-28 17:43:01,595 - ControlNet - INFO - ControlNet v1.1.441
2024-03-28 17:43:01,775 - ControlNet - INFO - ControlNet v1.1.441
sd-webui-prompt-all-in-one background API service started successfully.
*** Error loading script: train_tools.py
    Traceback (most recent call last):
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\scripts\train_tools.py", line 7, in <module>
        from liasece_sd_webui_train_tools.ui import *
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ui.py", line 16, in <module>
        from liasece_sd_webui_train_tools.train_ui import *
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 10, in <module>
        from liasece_sd_webui_train_tools import train
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train.py", line 8, in <module>
        from liasece_sd_webui_train_tools.ArgsList import ArgStore
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\ArgsList.py", line 23, in <module>
        import liasece_sd_webui_train_tools.sd_scripts.train_network as train_network
      File "D:\Program Files\sd-webui-a1111-v1-pre\webui\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\sd_scripts\train_network.py", line 10, in <module>
        import toml
    ModuleNotFoundError: No module named 'toml'

---
Loading weights [b363551a70] from D:\Program Files\sd-webui-a1111-v1-pre\webui\models\Stable-diffusion\LEOSAM FilmGirl Ultra.safetensors
[LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
Creating model from config: D:\Program Files\sd-webui-a1111-v1-pre\webui\configs\v1-inference.yaml
2024-03-28 17:43:05,427 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: False
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy:
Civitai Helper: use civitai api key: False
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.
Model loaded in 5.0s (load weights from disk: 0.2s, create model: 2.8s, apply weights to model: 1.3s, load textual inversion embeddings: 0.4s, calculate empty prompt: 0.2s).

To create a public link, set `share=True` in `launch()`.
Startup time: 42.3s (prepare environment: 16.7s, import torch: 5.4s, import gradio: 1.4s, setup paths: 1.5s, initialize shared: 0.3s, other imports: 0.9s, load scripts: 6.2s, create ui: 2.8s, gradio launch: 2.6s, add APIs: 1.9s, app_started_callback: 2.5s).
